name: 'setup-spatialos-cli'
description: 'Download and install the Spatial CLI.'
author: 'Jamie Brynes'
inputs:
  version:
    description: 'The version of the Spatial CLI to download.'
    default: 'latest'
  oauth_token:
    description: 'The service account oauth token to use for the Spatial CLI.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
